from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(794, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(794, 579))
        MainWindow.setBaseSize(QtCore.QSize(794, 579))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Asset/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(596, 395))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.appearance = QtWidgets.QFrame(self.centralwidget)
        self.appearance.setMinimumSize(QtCore.QSize(80, 40))
        self.appearance.setMaximumSize(QtCore.QSize(1000, 85))
        self.appearance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appearance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appearance.setObjectName("appearance")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.appearance)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_2 = SwitchControl (self.appearance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMaximumSize(QtCore.QSize(15, 300))
        self.checkBox_2.setStyleSheet("border-radius:10px;")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.label_4 = QtWidgets.QLabel(self.appearance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(188, 500))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_31.addWidget(self.appearance, 0, QtCore.Qt.AlignRight)
        self.header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(400, 95))
        self.header.setMaximumSize(QtCore.QSize(400, 95))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(1)
        self.header.setFont(font)
        self.header.setText("")
        self.header.setPixmap(QtGui.QPixmap("Asset/title_logo2.png"))
        self.header.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.header.setObjectName("header")
        self.verticalLayout_31.addWidget(self.header, 0, QtCore.Qt.AlignHCenter)
        self.pages = QtWidgets.QTabWidget(self.centralwidget)
        self.pages.setObjectName("pages")
        self.login_Tab = QtWidgets.QWidget()
        self.login_Tab.setObjectName("login_Tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_Tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_formframe = QtWidgets.QFrame(self.login_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_formframe.sizePolicy().hasHeightForWidth())
        self.login_formframe.setSizePolicy(sizePolicy)
        self.login_formframe.setMinimumSize(QtCore.QSize(759, 395))
        self.login_formframe.setMaximumSize(QtCore.QSize(1920, 1080))
        self.login_formframe.setBaseSize(QtCore.QSize(0, 0))
        self.login_formframe.setStyleSheet("background-color: rgb(4, 29, 45);\n"
"border-radius: 30px 30px 0px 0px;")
        self.login_formframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_formframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_formframe.setObjectName("login_formframe")
        self.lineEdit = QtWidgets.QLineEdit(self.login_formframe)
        self.lineEdit.setGeometry(QtCore.QRect(180, 70, 431, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.login_formframe)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 140, 431, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.login_formframe)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 171, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(21)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.login_formframe)
        self.pushButton.setGeometry(QtCore.QRect(330, 270, 121, 45))
        self.pushButton.setMinimumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: rgb(4, 29, 45);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius: 10px;\n"
"drop-shadow: 5px 5px blue;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.login_formframe)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(495, 220, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.login_formframe)
        self.label_3.setGeometry(QtCore.QRect(200, 400, 397, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgba(175, 175, 175, 50);")
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.login_formframe)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 220, 261, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.verticalLayout_2.addWidget(self.login_formframe, 0, QtCore.Qt.AlignHCenter)
        self.pages.addTab(self.login_Tab, "")
        self.admin_dashboard = QtWidgets.QWidget()
        self.admin_dashboard.setObjectName("admin_dashboard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.admin_dashboard)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.admin_navbar = QtWidgets.QFrame(self.admin_dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_navbar.sizePolicy().hasHeightForWidth())
        self.admin_navbar.setSizePolicy(sizePolicy)
        self.admin_navbar.setMinimumSize(QtCore.QSize(753, 0))
        self.admin_navbar.setMaximumSize(QtCore.QSize(748, 89))
        self.admin_navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_navbar.setObjectName("admin_navbar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.admin_navbar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.homeButton = QtWidgets.QPushButton(self.admin_navbar)
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.homeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Asset/icons8-home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setIconSize(QtCore.QSize(35, 60))
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout_2.addWidget(self.homeButton)
        self.pendingreqButton = QtWidgets.QPushButton(self.admin_navbar)
        self.pendingreqButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pendingreqButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.pendingreqButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Asset/clipboard-list-checklist-menu-check-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pendingreqButton.setIcon(icon2)
        self.pendingreqButton.setIconSize(QtCore.QSize(35, 60))
        self.pendingreqButton.setObjectName("pendingreqButton")
        self.horizontalLayout_2.addWidget(self.pendingreqButton)
        self.logsButton = QtWidgets.QPushButton(self.admin_navbar)
        self.logsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logsButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.logsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Asset/book-book-svgrepo-com (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logsButton.setIcon(icon3)
        self.logsButton.setIconSize(QtCore.QSize(35, 60))
        self.logsButton.setObjectName("logsButton")
        self.horizontalLayout_2.addWidget(self.logsButton)
        self.noticeButton = QtWidgets.QPushButton(self.admin_navbar)
        self.noticeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.noticeButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.noticeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Asset/announcement-svgrepo-com (2) - Copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noticeButton.setIcon(icon4)
        self.noticeButton.setIconSize(QtCore.QSize(35, 60))
        self.noticeButton.setObjectName("noticeButton")
        self.horizontalLayout_2.addWidget(self.noticeButton)
        self.verticalLayout_3.addWidget(self.admin_navbar, 0, QtCore.Qt.AlignHCenter)
        self.admin_hero = QtWidgets.QFrame(self.admin_dashboard)
        self.admin_hero.setMinimumSize(QtCore.QSize(0, 0))
        self.admin_hero.setStyleSheet("QFrame{\n"
"border: 2px solid rgb(4, 29, 45);\n"
"border-radius: 20px;\n"
"}")
        self.admin_hero.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_hero.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_hero.setObjectName("admin_hero")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.admin_hero)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.greet = QtWidgets.QLabel(self.admin_hero)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.greet.setFont(font)
        self.greet.setStyleSheet("border:none;")
        self.greet.setAlignment(QtCore.Qt.AlignCenter)
        self.greet.setObjectName("greet")
        self.verticalLayout_4.addWidget(self.greet)
        self.time = QtWidgets.QLabel(self.admin_hero)
        self.time.setMaximumSize(QtCore.QSize(16777215, 134))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.time.setFont(font)
        self.time.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(4, 29, 45);")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout_4.addWidget(self.time)
        self.date = QtWidgets.QLabel(self.admin_hero)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.date.setFont(font)
        self.date.setStyleSheet("border:none;")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.verticalLayout_4.addWidget(self.date)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.admin_hero)
        self.admin_logout = QtWidgets.QPushButton(self.admin_dashboard)
        self.admin_logout.setMaximumSize(QtCore.QSize(60, 60))
        self.admin_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.admin_logout.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.admin_logout.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Asset/logout-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admin_logout.setIcon(icon5)
        self.admin_logout.setIconSize(QtCore.QSize(37, 60))
        self.admin_logout.setObjectName("admin_logout")
        self.verticalLayout_3.addWidget(self.admin_logout)
        self.pages.addTab(self.admin_dashboard, "")
        self.admin_requests = QtWidgets.QWidget()
        self.admin_requests.setObjectName("admin_requests")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.admin_requests)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.admin_requests)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reservation_BTH = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH.sizePolicy().hasHeightForWidth())
        self.reservation_BTH.setSizePolicy(sizePolicy)
        self.reservation_BTH.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH.setMaximumSize(QtCore.QSize(66, 71))
        self.reservation_BTH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Asset/back-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reservation_BTH.setIcon(icon6)
        self.reservation_BTH.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH.setObjectName("reservation_BTH")
        self.horizontalLayout_5.addWidget(self.reservation_BTH)
        self.resevation_heading = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading.setFont(font)
        self.resevation_heading.setStyleSheet("")
        self.resevation_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading.setObjectName("resevation_heading")
        self.horizontalLayout_5.addWidget(self.resevation_heading)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.pages.addTab(self.admin_requests, "")
        self.admin_logs = QtWidgets.QWidget()
        self.admin_logs.setObjectName("admin_logs")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.admin_logs)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtWidgets.QFrame(self.admin_logs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.reservation_BTH_2 = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH_2.sizePolicy().hasHeightForWidth())
        self.reservation_BTH_2.setSizePolicy(sizePolicy)
        self.reservation_BTH_2.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH_2.setMaximumSize(QtCore.QSize(66, 71))
        self.reservation_BTH_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH_2.setText("")
        self.reservation_BTH_2.setIcon(icon6)
        self.reservation_BTH_2.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH_2.setObjectName("reservation_BTH_2")
        self.horizontalLayout_6.addWidget(self.reservation_BTH_2)
        self.resevation_heading_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading_2.setFont(font)
        self.resevation_heading_2.setStyleSheet("")
        self.resevation_heading_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_2.setObjectName("resevation_heading_2")
        self.horizontalLayout_6.addWidget(self.resevation_heading_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 1080))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.verticalLayout_9.addWidget(self.tableWidget_2)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.verticalLayout_12.addWidget(self.frame)
        self.pages.addTab(self.admin_logs, "")
        self.admin_notice = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_notice.sizePolicy().hasHeightForWidth())
        self.admin_notice.setSizePolicy(sizePolicy)
        self.admin_notice.setObjectName("admin_notice")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.admin_notice)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_7 = QtWidgets.QFrame(self.admin_notice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.reservation_BTH_3 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH_3.sizePolicy().hasHeightForWidth())
        self.reservation_BTH_3.setSizePolicy(sizePolicy)
        self.reservation_BTH_3.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH_3.setMaximumSize(QtCore.QSize(60, 65))
        self.reservation_BTH_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH_3.setText("")
        self.reservation_BTH_3.setIcon(icon6)
        self.reservation_BTH_3.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH_3.setObjectName("reservation_BTH_3")
        self.horizontalLayout_7.addWidget(self.reservation_BTH_3)
        self.resevation_heading_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading_3.setFont(font)
        self.resevation_heading_3.setStyleSheet("")
        self.resevation_heading_3.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_3.setObjectName("resevation_heading_3")
        self.horizontalLayout_7.addWidget(self.resevation_heading_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_15.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 39))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setMinimumSize(QtCore.QSize(40, 23))
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(4, 29, 45);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_8.addWidget(self.radioButton_6)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_8.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_8.addWidget(self.radioButton_5)
        self.verticalLayout_15.addWidget(self.frame_10, 0, QtCore.Qt.AlignHCenter)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 1080))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:1000px;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_14.addWidget(self.textEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(153, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:10px;\n"
"drop-shadow: 5px 5px blue;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_14.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_15.addWidget(self.frame_9)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.pages.addTab(self.admin_notice, "")
        self.user_dashboard = QtWidgets.QWidget()
        self.user_dashboard.setObjectName("user_dashboard")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.user_dashboard)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_11 = QtWidgets.QFrame(self.user_dashboard)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.admin_navbar_2 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_navbar_2.sizePolicy().hasHeightForWidth())
        self.admin_navbar_2.setSizePolicy(sizePolicy)
        self.admin_navbar_2.setMinimumSize(QtCore.QSize(753, 0))
        self.admin_navbar_2.setMaximumSize(QtCore.QSize(748, 89))
        self.admin_navbar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_navbar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_navbar_2.setObjectName("admin_navbar_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.admin_navbar_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.homeButton_2 = QtWidgets.QPushButton(self.admin_navbar_2)
        self.homeButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.homeButton_2.setText("")
        self.homeButton_2.setIcon(icon1)
        self.homeButton_2.setIconSize(QtCore.QSize(35, 60))
        self.homeButton_2.setObjectName("homeButton_2")
        self.horizontalLayout_10.addWidget(self.homeButton_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.admin_navbar_2)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.pushButton_8.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Asset/user-profile-filled-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(41, 60))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_10.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.admin_navbar_2)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border:none;\n"
"}")
        self.pushButton_7.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Asset/compose-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon8)
        self.pushButton_7.setIconSize(QtCore.QSize(35, 60))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_10.addWidget(self.pushButton_7)
        self.frame_13 = QtWidgets.QFrame(self.admin_navbar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(123, 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10.addWidget(self.frame_13)
        self.admin_logout_3 = QtWidgets.QPushButton(self.admin_navbar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_logout_3.sizePolicy().hasHeightForWidth())
        self.admin_logout_3.setSizePolicy(sizePolicy)
        self.admin_logout_3.setMaximumSize(QtCore.QSize(60, 60))
        self.admin_logout_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin_logout_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.admin_logout_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.admin_logout_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Asset/notification-bell-new-svgrepo-com (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admin_logout_3.setIcon(icon9)
        self.admin_logout_3.setIconSize(QtCore.QSize(37, 60))
        self.admin_logout_3.setObjectName("admin_logout_3")
        self.horizontalLayout_10.addWidget(self.admin_logout_3)
        self.admin_logout_4 = QtWidgets.QPushButton(self.admin_navbar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_logout_4.sizePolicy().hasHeightForWidth())
        self.admin_logout_4.setSizePolicy(sizePolicy)
        self.admin_logout_4.setMaximumSize(QtCore.QSize(60, 60))
        self.admin_logout_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin_logout_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.admin_logout_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.admin_logout_4.setText("")
        self.admin_logout_4.setIcon(icon5)
        self.admin_logout_4.setIconSize(QtCore.QSize(37, 60))
        self.admin_logout_4.setObjectName("admin_logout_4")
        self.horizontalLayout_10.addWidget(self.admin_logout_4)
        self.verticalLayout_19.addWidget(self.admin_navbar_2, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.admin_hero_2 = QtWidgets.QFrame(self.frame_12)
        self.admin_hero_2.setMinimumSize(QtCore.QSize(0, 0))
        self.admin_hero_2.setStyleSheet("border: 2px solid rgb(4, 29, 45);;\n"
"border-radius: 20px;")
        self.admin_hero_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_hero_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_hero_2.setObjectName("admin_hero_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.admin_hero_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.greet_2 = QtWidgets.QLabel(self.admin_hero_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(True)
        self.greet_2.setFont(font)
        self.greet_2.setStyleSheet("border:none;")
        self.greet_2.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_2.setObjectName("greet_2")
        self.verticalLayout_18.addWidget(self.greet_2)
        self.time_2 = QtWidgets.QLabel(self.admin_hero_2)
        self.time_2.setMaximumSize(QtCore.QSize(16777215, 134))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.time_2.setFont(font)
        self.time_2.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(4, 29, 45);")
        self.time_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_2.setObjectName("time_2")
        self.verticalLayout_18.addWidget(self.time_2)
        self.date_2 = QtWidgets.QLabel(self.admin_hero_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.date_2.setFont(font)
        self.date_2.setStyleSheet("border:none;")
        self.date_2.setAlignment(QtCore.Qt.AlignCenter)
        self.date_2.setObjectName("date_2")
        self.verticalLayout_18.addWidget(self.date_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.horizontalLayout_12.addWidget(self.admin_hero_2)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_12)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_12.addWidget(self.tableWidget_3)
        self.verticalLayout_19.addWidget(self.frame_12)
        self.verticalLayout_17.addWidget(self.frame_11)
        self.pages.addTab(self.user_dashboard, "")
        self.user_notifications = QtWidgets.QWidget()
        self.user_notifications.setObjectName("user_notifications")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.user_notifications)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_15 = QtWidgets.QFrame(self.user_notifications)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.reservation_BTH_4 = QtWidgets.QPushButton(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH_4.sizePolicy().hasHeightForWidth())
        self.reservation_BTH_4.setSizePolicy(sizePolicy)
        self.reservation_BTH_4.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH_4.setMaximumSize(QtCore.QSize(66, 71))
        self.reservation_BTH_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH_4.setText("")
        self.reservation_BTH_4.setIcon(icon6)
        self.reservation_BTH_4.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH_4.setObjectName("reservation_BTH_4")
        self.horizontalLayout_11.addWidget(self.reservation_BTH_4)
        self.resevation_heading_4 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading_4.setFont(font)
        self.resevation_heading_4.setStyleSheet("")
        self.resevation_heading_4.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_4.setObjectName("resevation_heading_4")
        self.horizontalLayout_11.addWidget(self.resevation_heading_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_20.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 1080))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.frame_17)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        self.verticalLayout_22.addWidget(self.tableWidget_6)
        self.verticalLayout.addWidget(self.frame_17)
        self.verticalLayout_21.addWidget(self.frame_15)
        self.pages.addTab(self.user_notifications, "")
        self.user_profile = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_profile.sizePolicy().hasHeightForWidth())
        self.user_profile.setSizePolicy(sizePolicy)
        self.user_profile.setObjectName("user_profile")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.user_profile)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_14 = QtWidgets.QFrame(self.user_profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.reservation_BTH_5 = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH_5.sizePolicy().hasHeightForWidth())
        self.reservation_BTH_5.setSizePolicy(sizePolicy)
        self.reservation_BTH_5.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH_5.setMaximumSize(QtCore.QSize(66, 71))
        self.reservation_BTH_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH_5.setText("")
        self.reservation_BTH_5.setIcon(icon6)
        self.reservation_BTH_5.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH_5.setObjectName("reservation_BTH_5")
        self.horizontalLayout_13.addWidget(self.reservation_BTH_5)
        self.resevation_heading_5 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading_5.setFont(font)
        self.resevation_heading_5.setStyleSheet("")
        self.resevation_heading_5.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_5.setObjectName("resevation_heading_5")
        self.horizontalLayout_13.addWidget(self.resevation_heading_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_24.addLayout(self.horizontalLayout_13)
        self.verticalLayout_23.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_14)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(227, 227, 227);\n"
"")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMinimumSize(QtCore.QSize(450, 85))
        self.frame_22.setMaximumSize(QtCore.QSize(2000, 85))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.resevation_heading_6 = QtWidgets.QLabel(self.frame_22)
        self.resevation_heading_6.setGeometry(QtCore.QRect(150, 20, 223, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resevation_heading_6.sizePolicy().hasHeightForWidth())
        self.resevation_heading_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        self.resevation_heading_6.setFont(font)
        self.resevation_heading_6.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_6.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_6.setObjectName("resevation_heading_6")
        self.label_6 = QtWidgets.QLabel(self.frame_22)
        self.label_6.setGeometry(QtCore.QRect(60, 0, 71, 76))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 76))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid #007ACC;\n"
"border-radius: 25px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_25.addWidget(self.frame_22, 0, QtCore.Qt.AlignHCenter)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(223, 129))
        self.frame_21.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setContentsMargins(-1, -1, -1, 34)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.resevation_heading_7 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_7.setFont(font)
        self.resevation_heading_7.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_7.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_7.setObjectName("resevation_heading_7")
        self.horizontalLayout_17.addWidget(self.resevation_heading_7, 0, QtCore.Qt.AlignLeft)
        self.resevation_heading_10 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_10.setFont(font)
        self.resevation_heading_10.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_10.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_10.setObjectName("resevation_heading_10")
        self.horizontalLayout_17.addWidget(self.resevation_heading_10, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_26.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.resevation_heading_8 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_8.setFont(font)
        self.resevation_heading_8.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_8.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_8.setObjectName("resevation_heading_8")
        self.horizontalLayout_16.addWidget(self.resevation_heading_8, 0, QtCore.Qt.AlignLeft)
        self.resevation_heading_11 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_11.setFont(font)
        self.resevation_heading_11.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_11.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_11.setObjectName("resevation_heading_11")
        self.horizontalLayout_16.addWidget(self.resevation_heading_11)
        self.verticalLayout_26.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.resevation_heading_9 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_9.setFont(font)
        self.resevation_heading_9.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_9.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_9.setObjectName("resevation_heading_9")
        self.horizontalLayout_15.addWidget(self.resevation_heading_9, 0, QtCore.Qt.AlignLeft)
        self.resevation_heading_13 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_13.setFont(font)
        self.resevation_heading_13.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_13.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_13.setObjectName("resevation_heading_13")
        self.horizontalLayout_15.addWidget(self.resevation_heading_13)
        self.verticalLayout_26.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.resevation_heading_14 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_14.setFont(font)
        self.resevation_heading_14.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_14.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_14.setObjectName("resevation_heading_14")
        self.horizontalLayout_14.addWidget(self.resevation_heading_14, 0, QtCore.Qt.AlignLeft)
        self.resevation_heading_12 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        self.resevation_heading_12.setFont(font)
        self.resevation_heading_12.setStyleSheet("color:rgba(4, 29, 45);\n"
"color: rgb(154, 154, 154);\n"
"\n"
"border:none;")
        self.resevation_heading_12.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_12.setObjectName("resevation_heading_12")
        self.horizontalLayout_14.addWidget(self.resevation_heading_12)
        self.verticalLayout_26.addLayout(self.horizontalLayout_14)
        self.verticalLayout_29.addLayout(self.verticalLayout_26)
        self.verticalLayout_25.addWidget(self.frame_21, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_28.addWidget(self.frame_20)
        self.verticalLayout_23.addWidget(self.frame_19)
        self.verticalLayout_27.addWidget(self.frame_14)
        self.pages.addTab(self.user_profile, "")
        self.user_apply = QtWidgets.QWidget()
        self.user_apply.setObjectName("user_apply")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.user_apply)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_23 = QtWidgets.QFrame(self.user_apply)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 41))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setSpacing(9)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.reservation_BTH_6 = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservation_BTH_6.sizePolicy().hasHeightForWidth())
        self.reservation_BTH_6.setSizePolicy(sizePolicy)
        self.reservation_BTH_6.setMinimumSize(QtCore.QSize(0, 0))
        self.reservation_BTH_6.setMaximumSize(QtCore.QSize(66, 71))
        self.reservation_BTH_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reservation_BTH_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reservation_BTH_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.reservation_BTH_6.setText("")
        self.reservation_BTH_6.setIcon(icon6)
        self.reservation_BTH_6.setIconSize(QtCore.QSize(40, 60))
        self.reservation_BTH_6.setObjectName("reservation_BTH_6")
        self.horizontalLayout_18.addWidget(self.reservation_BTH_6)
        self.resevation_heading_15 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        self.resevation_heading_15.setFont(font)
        self.resevation_heading_15.setStyleSheet("")
        self.resevation_heading_15.setAlignment(QtCore.Qt.AlignCenter)
        self.resevation_heading_15.setObjectName("resevation_heading_15")
        self.horizontalLayout_18.addWidget(self.resevation_heading_15, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(31, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(106, 100))
        self.lineEdit_3.setStyleSheet("border-radius:10px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_18.addWidget(self.lineEdit_3)
        self.power_search = QtWidgets.QPushButton(self.frame_23)
        self.power_search.setEnabled(False)
        self.power_search.setMaximumSize(QtCore.QSize(66, 71))
        self.power_search.setStyleSheet("QPushButton{\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:20px;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 79, 167);\n"
"border-radius:20px;\n"
"border:none;\n"
"}")
        self.power_search.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Asset/search-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.power_search.setIcon(icon10)
        self.power_search.setIconSize(QtCore.QSize(50, 27))
        self.power_search.setObjectName("power_search")
        self.horizontalLayout_18.addWidget(self.power_search)
        self.horizontalLayout_18.setStretch(2, 100)
        self.verticalLayout_35.addLayout(self.horizontalLayout_18)
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(9)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_7 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_30.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.comboBox.setFont(font)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_30.addWidget(self.comboBox)
        self.horizontalLayout_19.addLayout(self.verticalLayout_30)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setSpacing(9)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_8 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_32.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_32.addWidget(self.comboBox_2)
        self.horizontalLayout_19.addLayout(self.verticalLayout_32)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_11 = QtWidgets.QLabel(self.frame_25)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_38.addWidget(self.label_11, 0, QtCore.Qt.AlignTop)
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_25)
        self.timeEdit.setMinimumSize(QtCore.QSize(85, 50))
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_38.addWidget(self.timeEdit)
        self.horizontalLayout_19.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_12 = QtWidgets.QLabel(self.frame_25)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_39.addWidget(self.label_12)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame_25)
        self.timeEdit_2.setMinimumSize(QtCore.QSize(85, 50))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.verticalLayout_39.addWidget(self.timeEdit_2)
        self.horizontalLayout_19.addLayout(self.verticalLayout_39)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_10 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_37.addWidget(self.label_10)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_37.addWidget(self.comboBox_3)
        self.horizontalLayout_19.addLayout(self.verticalLayout_37)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setSpacing(6)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_9 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_33.addWidget(self.label_9)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_25)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 53))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_33.addWidget(self.dateEdit)
        self.horizontalLayout_19.addLayout(self.verticalLayout_33)
        self.verticalLayout_35.addWidget(self.frame_25)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_24)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 267))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 500))
        self.plainTextEdit.setStyleSheet("\n"
"")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_36.addWidget(self.plainTextEdit)
        self.verticalLayout_35.addWidget(self.frame_24)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(500, 42))
        self.pushButton_3.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(4, 29, 45);\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:10px;\n"
"drop-shadow: 5px 5px blue;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_35.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_34.addWidget(self.frame_23)
        self.pages.addTab(self.user_apply, "")
        self.verticalLayout_31.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.menubar.setFont(font)
        self.menubar.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.menubar.setStyleSheet("QMenuBar {\n"
"    \n"
"    color: rgb(255, 0, 0);\n"
"    background-color: rgb(11, 79, 167);\n"
"}\n"
"QMenuBar:hover {\n"
"    color:rgb(0,0,0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuApp = QtWidgets.QMenu(self.menubar)
        self.menuApp.setStyleSheet("QMenu::item:selected {\n"
"    background-color: rgb(179, 179, 179);\n"
"}")
        self.menuApp.setObjectName("menuApp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Downloads/about-filled-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon11)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionForce_Exit = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../Downloads/switch-off-on-power-energy-battery-ecology-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForce_Exit.setIcon(icon12)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.actionForce_Exit.setFont(font)
        self.actionForce_Exit.setObjectName("actionForce_Exit")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setCheckable(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../Downloads/update-rotation-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon13)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.actionRefresh.setFont(font)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuApp.addAction(self.actionRefresh)
        self.menuApp.addAction(self.actionAbout)
        self.menuApp.addAction(self.actionForce_Exit)
        self.menubar.addAction(self.menuApp.menuAction())

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        self.admin_logout.clicked.connect(self.centralwidget.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Campus Resource Management System (CRMS)"))
        self.label_4.setText(_translate("MainWindow", "  Dark Mode"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Welcome"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.checkBox.setToolTip(_translate("MainWindow", "This feature is coming soon"))
        self.checkBox.setText(_translate("MainWindow", "Remember Me"))
        self.label_3.setText(_translate("MainWindow", "CRMS V1.3 Beta | Developed By Group 5"))
        self.radioButton.setText(_translate("MainWindow", "Admin"))
        self.radioButton_2.setText(_translate("MainWindow", "Student"))
        self.radioButton_3.setText(_translate("MainWindow", "Teacher"))
        self.pages.setTabText(self.pages.indexOf(self.login_Tab), _translate("MainWindow", "Tab 1"))
        self.homeButton.setToolTip(_translate("MainWindow", "Home"))
        self.pendingreqButton.setToolTip(_translate("MainWindow", "Reservation Requests"))
        self.logsButton.setToolTip(_translate("MainWindow", "Application Logs"))
        self.noticeButton.setToolTip(_translate("MainWindow", "Notice Board"))
        self.greet.setText(_translate("MainWindow", "Good Morning"))
        self.time.setText(_translate("MainWindow", "HH:MM AM/PM"))
        self.date.setText(_translate("MainWindow", "DD:MM:YY"))
        self.pages.setTabText(self.pages.indexOf(self.admin_dashboard), _translate("MainWindow", "Tab 2"))
        self.reservation_BTH.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading.setText(_translate("MainWindow", "Reservation Requests"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Applicant"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Resource"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Notes"))
        self.pages.setTabText(self.pages.indexOf(self.admin_requests), _translate("MainWindow", "Tab 3"))
        self.reservation_BTH_2.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading_2.setText(_translate("MainWindow", "Application Logs"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Override Status"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Applicant"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Resource"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Notes"))
        self.pages.setTabText(self.pages.indexOf(self.admin_logs), _translate("MainWindow", "Tab 4"))
        self.reservation_BTH_3.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading_3.setText(_translate("MainWindow", "Compose a Notice"))
        self.label.setText(_translate("MainWindow", "To: "))
        self.radioButton_6.setText(_translate("MainWindow", "Everyone"))
        self.radioButton_4.setText(_translate("MainWindow", "Teacher"))
        self.radioButton_5.setText(_translate("MainWindow", "Students"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Write something"))
        self.pushButton_2.setText(_translate("MainWindow", "Publish"))
        self.pages.setTabText(self.pages.indexOf(self.admin_notice), _translate("MainWindow", "Tab 5"))
        self.homeButton_2.setToolTip(_translate("MainWindow", "Home"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "Profile"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "Apply for Reservation"))
        self.admin_logout_3.setToolTip(_translate("MainWindow", "Notifications"))
        self.admin_logout_4.setToolTip(_translate("MainWindow", "Log Out"))
        self.label_5.setText(_translate("MainWindow", "Notices"))
        self.greet_2.setText(_translate("MainWindow", "Welcome [Username]"))
        self.time_2.setText(_translate("MainWindow", "HH:MM AM/PM"))
        self.date_2.setText(_translate("MainWindow", "DD:MM:YY"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Message"))
        self.pages.setTabText(self.pages.indexOf(self.user_dashboard), _translate("MainWindow", "Tab 6"))
        self.reservation_BTH_4.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading_4.setText(_translate("MainWindow", "Notifications"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Reviewed On"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Resource"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Notes"))
        self.pages.setTabText(self.pages.indexOf(self.user_notifications), _translate("MainWindow", "Tab 7"))
        self.reservation_BTH_5.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading_5.setText(_translate("MainWindow", "User Profile"))
        self.resevation_heading_6.setText(_translate("MainWindow", "f_Name l_Name"))
        self.resevation_heading_7.setText(_translate("MainWindow", "Role:"))
        self.resevation_heading_10.setText(_translate("MainWindow", "$$$$$$$$$$$"))
        self.resevation_heading_8.setText(_translate("MainWindow", "Dept:"))
        self.resevation_heading_11.setText(_translate("MainWindow", "$$$$$"))
        self.resevation_heading_9.setText(_translate("MainWindow", "ID"))
        self.resevation_heading_13.setText(_translate("MainWindow", "$$$$$$$$$$$"))
        self.resevation_heading_14.setText(_translate("MainWindow", "Flags"))
        self.resevation_heading_12.setText(_translate("MainWindow", "No"))
        self.pages.setTabText(self.pages.indexOf(self.user_profile), _translate("MainWindow", "Tab 8"))
        self.reservation_BTH_6.setToolTip(_translate("MainWindow", "Go back to home"))
        self.resevation_heading_15.setText(_translate("MainWindow", "Apply for a Reservation"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Search"))
        self.power_search.setToolTip(_translate("MainWindow", "This feature is coming soon"))
        self.label_7.setText(_translate("MainWindow", "Resource"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "Select Resource type"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Classroom"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Conference Hall"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Playground"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Transportation"))
        self.label_8.setText(_translate("MainWindow", "Space"))
        self.comboBox_2.setPlaceholderText(_translate("MainWindow", "Specify your requirement"))
        self.label_11.setText(_translate("MainWindow", "Start Time"))
        self.label_12.setText(_translate("MainWindow", "End Time"))
        self.label_10.setText(_translate("MainWindow", "Time Slot"))
        self.comboBox_3.setPlaceholderText(_translate("MainWindow", "Specify your requirement"))
        self.label_9.setText(_translate("MainWindow", "Date"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Write a note(Optional)"))
        self.pushButton_3.setText(_translate("MainWindow", "Apply"))
        self.pages.setTabText(self.pages.indexOf(self.user_apply), _translate("MainWindow", "Tab 9"))
        self.menuApp.setTitle(_translate("MainWindow", "App"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionForce_Exit.setText(_translate("MainWindow", "Force Exit"))
        self.actionForce_Exit.setShortcut(_translate("MainWindow", "Alt+Q"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setShortcut(_translate("MainWindow", "Ctrl+S"))
from toggle_switch import SwitchControl 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
